---
logging:
  category:
    - Logging
  application_init:
    block:
      text:
        - Initialize Logging
    code:
      - twr_log_init(TWR_LOG_LEVEL_DUMP, TWR_LOG_TIMESTAMP_ABS);
      - twr_log_info("APPLICATION START");
  action:
    info:
      block:
        colour: '#008000'
        text:
          - Log Info %1
          - 'Message: %2 %3'
          - 'Variable %4'
        arguments:
          X:
            type: new_line
          MESSAGE:
            type: text
            value: info
          Y:
            type: new_line
          VARIABLE:
            type: input
      code:
        - twr_log_info("{MESSAGE} {FORMAT_STRING}", {VARIABLE});
    debug:
      block:
        colour: '#BF40BF'
        text:
          - Log Debug %1
          - 'Message: %2 %3'
          - 'Variable %4'
        arguments:
          X:
            type: new_line
          MESSAGE:
            type: text
            value: debug
          Y:
            type: new_line
          VARIABLE:
            type: input
      code:
        - twr_log_debug("{MESSAGE} {FORMAT_STRING}", {VARIABLE});
    error:
      block:
        colour: '#FF0000'
        text:
          - Log Error %1
          - 'Message: %2 %3'
          - 'Variable %4'
        arguments:
          X:
            type: new_line
          MESSAGE:
            type: text
            value: error
          Y:
            type: new_line
          VARIABLE:
            type: input
      code:
        - twr_log_error("{MESSAGE} {FORMAT_STRING}", {VARIABLE});
    warning:
      block:
        colour: '#FFA500'
        text:
          - Log Warning %1
          - 'Message: %2 %3'
          - 'Variable %4'
        arguments:
          X:
            type: new_line
          MESSAGE:
            type: text
            value: warning
          Y:
            type: new_line
          VARIABLE:
            type: input
      code:
        - twr_log_warning("{MESSAGE} {FORMAT_STRING}", {VARIABLE});
